version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/hoshinotsuyoshi/go-wc
    steps:
      - checkout
      - run:
          name: make all
          command: make all
      - run:
          name: make test-all
          command: make test-all
